### ISSUE TITLE
Quest 'Vampirism' Unclear

### ISSUE THREAD

**Issue by PaladinOne** [DrasticDemise/Simply-Magic#10]
The 'Vampirism' quest in the Witchery quest line requires the book Observations of an Immortal. In particular, it requires the version that has been upgraded with a torn page. Unfortunately, even with this version (metadata:1) the quest does not complete. (Examining further, the quest requests a metadata:9 variant, which I assume requires several additional torn pages to acquire.) I'm not sure yet if the quest objective needs a correction, or the quest information needs a correction, but simply crafting an Observations of an Immortal with a Torn Page does not complete the quest.

**Comment by DrasticDemise** [comment]
Fixed, thank you for the report. I will push an update shortly.
