### ISSUE TITLE
General Feedback

### ISSUE THREAD

**Issue by uberwookie** [DrasticDemise/Simply-Magic#14]
The iron tools being usable for crafting only is not very good for balance. Most people when they start tend to want to make a little home and rush simple iron tools to do so. In addition, it is artificially inflating tedium by making you take longer to dig/mine in the beginning of the game when most magical tools are simply unusable. The amount of resources needed to obtain higher tools such as thaumium or manasteel (the two easiest variants to obtain) is still pretty high for a beginning player (To the server/world seed)

Suggested fix for aforementioned, enchanted stone tools with high unbreaking and efficiency for the simple rewards in the info and challenge chapter. After all, you want players to get into the 'meat' of the pack ASAP.

Might want to have a "Start here" information chapter that breaks down the new changes (Make information Chapter 1 instead of the last chapter, and challenges can stay the last chapter.)

I would also suggest a "Getting Started" chapter for your first one that is basically all the step 1 quests in one chapter... get a wand and Thaumonomicon, botanica lexica, blood magic book, etc, to start players on each path just a bit. 

Also, reward players books maybe, since it can be difficult to set up that infrastructure based on the world seed immediately. Its too easy to not have access to sugar cane or leather for the first in game week or so.

Right now the mod kinda assumes you have an established home base, but it also makes it a bit tedious to do so by not allowing iron tools. Honestly, It might not be a bad idea to have a "Starter home" detection quest for 64 cobble, 64 vanilla planks, 16 torches, crafting table, furnace, a door, and get rewards like a few bookshelves, maybe 2 spawn eggs of each passive, and a few loaves of bread and some vanilla seeds of each kind to skip the tedious parts of the new game for an optional quest for veteran players.

**Comment by BrizzleMFD** [comment]
We have play tested and I think we are going to leave iron tools as is. I had thaumium very quick. With one stone pick you can get all the iron needed for a crucible and the wand. Thaumium I feel is super easy to obtain. Drastic might feel differently but for me I feel we have the pack balanced around vanilla. In vanilla if you need books you just have to find them or making them and the same will be true here.

**Comment by DrasticDemise** [comment]
Thank you for the feedback. I will set up a Straw Poll over Iron Tools which will be available in-game via Yampst Link the next time you log on.

**Comment by uberwookie** [comment]
Thaumium and manasteel aren't terribly hard to get, once you have an established base. Its the... making a place that is your home that is tedious with stone tools. (which is why I suggest giving some enchanted stone tools for early quest rewards, so they will last long enough to carve out a base to get the other stuff)

**Comment by BrizzleMFD** [comment]
That idea I do like a lot. I'll think a little bit and talk to drastic about it to figure out how we feel it should happen. Maybe it would be in you inventory on start.

**Comment by Zieg777** [comment]
I feel I should put in my $0.02. An AM2 Dig spell is an infinite durability Iron pick. I was able to make mine with only needing to make one additional iron pick (need it for vinteum, chimerite, and blue topaz)

**Comment by BrizzleMFD** [comment]
Thanks for the heads up.
