### ISSUE TITLE
Clarify that the Throw Me item will give a Golemancer's Bell.

### ISSUE THREAD

**Issue by SilventheThrid** [DrasticDemise/Simply-Magic#17]
Both items share the same recipe and if i try to craft a Golemancer's bell in the arcane worktable it still takes Vis from my wand but crafts a Throw me.

**Comment by DrasticDemise** [comment]
Tossing the quandrum item will give you a golemancers bell. This is a hacky fix for servers because the Golemancers Bell causes a Crash to Desktop on a server.

**Comment by SilventheThrid** [comment]
ok, thanks for the info
