### ISSUE TITLE
[Suggestion] Diamond Dolly - make it end game ish

### ISSUE THREAD

**Issue by koalalord9999** [DrasticDemise/Simply-Magic#35]
I'm on a server, we havn't updated to 1.1.2 yet, so I'm not entierly sure if this has had any changes to it, but I think the dolly should be a late game upgrade to the regular dolly. possibly through botania, BM, and Thaumcraft combined. 

It could be crafted in the Thaumcraft Infusion Altar using 2 of each: Void Metal, Terra Steel, Demon Blood Shard and Demon Heart. Also, having it cost +1 of each final combination Rune from Botania (Greed, lust, sloth etc) 128 of each primal Essentia, 256 Praecantatio, and 256 Vaccuos. the catalyst would obviously be a regular dolly.

And if the dolly isn't already changed, if possible attempt to remove all diamond dollies from a map - when updating to the newest version, so you need to remake the dolly.

**Comment by BrizzleMFD** [comment]
I don't know that our goal here is really like a magical infinity evolved, the things we nerfed was to puch players into using the mod items rather then vanilla tools and such. I however am open minded and would love to take opinions from others. There is always if we wanted to the ability to make a hard version of the pack with in the original( just like infinity)

**Comment by koalalord9999** [comment]
:O How did you know where I was going with that! But in all seriousness, I agree, we don't really need another Infinity Evolved Expert (Granted it would be great, and would put it out there that doing so, isn't impossible, and more packs may come with an expert equivlent) I just feel that  the Diamond dolly is too overpowered in a pack without mechanical automation (Particularly Ender IO because of its any spawner thing). I would rather have it disabled then use it for super super cheap, only because the ability to move spawners is a huge game changer in a lot of ways, skips progression through nether, makes most things that use glowstone trivial (early game) and with runic dungeons, makes the end pretty much worthless

**Comment by DrasticDemise** [comment]
The Diamond Dolly is disabled by default in the pack. Alternatives exist in Thaumcraft and Botania that allow for spawner creation and movement.
