### ISSUE TITLE
[Proposal] Add Thaumcraft Node Tracker

### ISSUE THREAD

**Issue by DrasticDemise** [DrasticDemise/Simply-Magic#39]
Most requested mod. Please post any pros or cons below and answer this quick strawpoll:http://strawpoll.me/6735799

**Comment by koalalord9999** [comment]
Well, I don't actually know too much about the mod, except it makes it so I don't have to spam my Minimap with waypoints - so that's a plus.

**Comment by DrasticDemise** [comment]
Added.
