### ISSUE TITLE
Adding Mouse Tweaks for 1.1.3?

### ISSUE THREAD

**Issue by koalalord9999** [DrasticDemise/Simply-Magic#40]
Hey there demise, if you could add Mouse Tweaks to the 1.1.3 update, that would be great!
Also, if you do add it, please use this config as it fixes a compatibility issue with Inventory Tweaks (scrolling to pull items from a chest) - It's a week duration, so copy it as soon as possible IF you plan on doing this.
http://pastebin.com/3DsHn2FB
Link to mousetweaks is here: http://minecraft.curseforge.com/projects/mouse-tweaks/files/2209265

**Comment by DrasticDemise** [comment]
Added. Thank you for your suggestion.
