### ISSUE TITLE
[Proposal] Chunk Loader mod

### ISSUE THREAD

**Issue by DrasticDemise** [DrasticDemise/Simply-Magic#41]
Any suggestions of feedback, please post below.

**Comment by koalalord9999** [comment]
Witchery already has a chunk loader - the poppet shelf. If you were to add one, I would use FTB Utilities, as it adds in personal chunk loaders, that can be maintained, and easily disabled by servers or singleplayer.

**Comment by DrasticDemise** [comment]
Added FTB Utilities
