### ISSUE TITLE
[Quest Bug] Crafting Scepters Again

### ISSUE THREAD

**Issue by Final-Legacy** [DrasticDemise/Simply-Magic#46]
I know you fixed the crafting scepters quest, but it only works to a degree. I hate to be a nuisance but the quest only recognizes the scepter if it is drained of all its vis. Just thought I'd let you know!

**Comment by BrizzleMFD** [comment]
Should it not be empty when you craft it?

**Comment by DrasticDemise** [comment]
There is no way to set the scepter to fuzzy detection, otherwise it will detect all types of wands instead of just the scepter. This is really just a fix to new players, not much I can for those who already made it and found it did not work.
