### ISSUE TITLE
Throw Me item for Golemancer's Bell returns wrong item

### ISSUE THREAD

**Issue by esotericist** [DrasticDemise/Simply-Magic#47]
I crafted the 'Throw Me' item, threw it, and got the following in chat:

Warning: Using numeric IDs will not be supported in the future. Please use names, such as 'Thaumcraft:BootsTraveller'

... and sure enough, I got boots of the traveller. Two copies of it, in fact.

**Comment by DrasticDemise** [comment]
Have you added any mods or removed any?

**Comment by BrizzleMFD** [comment]
Fixed in dev
