### ISSUE TITLE
Update 1.1.4

### ISSUE THREAD

**Issue by DrasticDemise** [DrasticDemise/Simply-Magic#49]
Updated: AOBD, AppleCore, Morpheus, Open Blocks/Lib
Added Storage Drawers, Thaumic Exploration
Fixed Potion ID's
Lowered Morpheus Requirement
Golemancers Bell Script Modified - May work, may not. @BrizzleMFD 
Fixed Golem Detection #48

**Comment by koalalord9999** [comment]
I know you post the change logs here, but if you could copy paste this into the curseforge change logs area when the update is released, that would be nice too ;)

**Comment by BrizzleMFD** [comment]
Sorry I did that for sm2 I forgot for sm1 I'll do that in a bit
