### ISSUE TITLE
Botania Runic Altar: duplicates tier 1 runes when you create tier 2 runes

### ISSUE THREAD

**Issue by maggotmick** [DrasticDemise/Simply-Magic#53]
Everytime i create autum, winter, summer and spring runes, the altar give me back fire, earth water and air runes (it depends on what rune you use to create the new rune), as far as i know that doesn't supposed to happen. Thanks!

Example 

Rune of Winter = 2 Snow Blocks, 1 Wool, 1 Cake, 1 Rune of Earth, 1 Rune of Water

That recipe give me back the Rune of Winter, 1 Rune of Earth and 1 Rune of Water

**Comment by jacobbridges** [comment]
This was in a recent update to Botania, Vazkii decided for re-usable runes -- but only in runic altar recipes!

**Comment by maggotmick** [comment]
Ohh thats nice, well i guess will continue with my progression in the mod =D
