### ISSUE TITLE
Upgrading server from 1.1.2 to 1.1.4

### ISSUE THREAD

**Issue by jacobbridges** [DrasticDemise/Simply-Magic#54]
Hey All,

Anyone know how to update a server running Simply Magic 1.1.2 to Simply Magic 1.1.4? The members of my server would like chunk loading which became available in Simple Magic 1.1.3.

**Comment by koalalord9999** [comment]
I think you just overwrite the mods in the mods folder for the server and you're good.. Not entierly sure though, I just play on one, not host ;)

**Comment by maggotmick** [comment]
I'll try thanks

**Comment by DrasticDemise** [comment]
Updating server versions is simply a matter of replacing the scripts, configs and mods folder with the folders of the latest version. If blocks or items are missing you may be required to do /fml confirm in the console if the server holds up during start.
