### ISSUE TITLE
Arcane Worktable+NEI Recipe Shiftclick=Crashlog

### ISSUE THREAD

**Issue by Larear** [DrasticDemise/Simply-Magic#56]
When I want to shift leftclick a recipe into an Arcane worktable the game crashes
It looks like the recipe tries to put the items from the top right corner into the spot below, At least thats what I can see in game when I click the [?] without shift. 
A normal crafting table doesn't crash.

http://pastebin.com/VVbpAbJd

**Comment by DrasticDemise** [comment]
This is a known issue, nothing I am able to fix.
