### ISSUE TITLE
Convocation of the Damned

### ISSUE THREAD

**Issue by danigirl100** [DrasticDemise/Simply-Magic#67]
Unable to start ritual even though all requirements are met.
15 mil LP - check (actually have more than 15 mil lp)
ritual set up by diviner - check
8 belljars with correct reagents - check
belljars linked to relays - check
relays linked to master ritual stone - check
Awakened Activation Crystal - check

When crystal is used on master ritual stone, message "You feel a pull, but are too weak to push any further"
Very frustrated right now about the situation.

**Comment by RealKC** [comment]
Is the Awakened Activation Crystal bound to yourself?

**Comment by danigirl100** [comment]
Thank you, that was the issue
