### ISSUE TITLE
Iron sword disappearing.

### ISSUE THREAD

**Issue by lokiregnarok** [DrasticDemise/Simply-Magic#68]
ok. this is not a big problem but...

it appears that my iron sword will always vanish while whacking zombies and skeletons.. doesn't happen on other swords. just the iron ones. Not sure if it is a mod doing it or it's just a glitch

**Comment by DrasticDemise** [comment]
Iron tools are disabled or nerfed heavily, more information is available in the information section of the quest book.

**Comment by lokiregnarok** [comment]
which... means i will need to make botania tools and weapons ... great thx. =)

**Comment by BrizzleMFD** [comment]
That was the idea.  Magic tutorial pack so we push you away from vanilla
