### ISSUE TITLE
[Proposal] AM2 Materials to the Challenge list.

### ISSUE THREAD

**Issue by Zieg777** [DrasticDemise/Simply-Magic#8]
10,000 Vinteum dust (or in block form if you want to require crafting too) isn't that hard to get for dust if you've got calefactors burning. They produce more than they consume if you set it right (as in, add one of any of the upgrades, even putting pillars around your obelisk is enough)

Similarly, witchwood wood would be a good one. The trees only grow in certain conditions (surround the dirt block your sapling is on with liquid essence). This would require both tree farming as well as knowledge of how they grow. The sapling drop rate is pretty low. I mean to do testing to see if Wizards autumn with prosperity can increase that rate.

Sunstone or Moonstone. Hmm. Moonstone is *infinite*, but just takes a while. In Hubris, I've got about 100 blocks of it though, and thats without using the lunar tides focus. Kinda farmable, I've been meaning to test a design to automate gathering it as well. I think the Blood Magic ore meteor can have these two ores.

Botania can generate most regular ores, including Blue Topaz and Chimerite. I don't know if that's worth a hoarding quest though.

Potion bundles could be a fun quest for automation. Seeds, sugar, and a potion make the lowest. Automating a potion is pretty easy. Craft those to get the Lesser potion. Lesser potion + gunpowder is standard. Standard + Vinteum is greater (or could do mana martinis, but those actually stack I think) Epic potions are greater and an arcane ash (stone, netherrack, glowstone, redstone). These are still easily automatable/able to be created/farmed. Legendary = Epic and Purified Vinteum (Vinteum, Arcane Ash, Desert Nova, Cerublossom.  All of this could be automated (if you add AM2 Plant fix of course). A bundle is just 3 potions and a string.

I think 1000 Legendary (bundles or even just potions) would be an amazing feat for automation. I've been told magic lets you do things, but tech lets things be done for you. Lets prove them wrong.

**Comment by DrasticDemise** [comment]
Approved, can be merged with Issue #7

**Comment by Zieg777** [comment]
Not exactly related, but while I'm here, The AM2 questline I gave you is in the top level directory instead of down where it goes in config/hqm.

Also. At least one of the quests I wrote could probably be moved to challenges. The "collect them all" for each of the guardians' gear kind of fits the theme of collections.

**Comment by DrasticDemise** [comment]
Added
