### ISSUE TITLE
Other AM2 quests not showing up

### ISSUE THREAD

**Issue by Zieg777** [DrasticDemise/Simply-Magic#9]
Not sure if its something in how I set the quests or what, but I cant get the quests to unlock. I had tried to set it so that most of it was hidden until you make the obelisk quest, but I think I set that quest to be hidden.. I'm apparently pretty awesome at writing quests.

**Comment by DrasticDemise** [comment]
How long ago did you update the pack?

**Comment by Zieg777** [comment]
Thank you! Hopefully not too many people got 1.0.1 before catching that
